### ISSUE TITLE
Export as curl command

### ISSUE THREAD

**Issue by OJFord** [asciimoo/wuzz#10]
Love this, great work!

Would be awesome to have a command to 'export as curl command', so that after finding the right request it could be easily copied to a shell script, for example.

Even more awesome, if this were sort of 'adapter' based, there could be (perhaps as contributed plugins) other export formats, such as for Python's requests library, etc.

**Comment by PouuleT** [comment]
Hello! I'd like to work on that part if that's ok
What would be the best approach ? Add some options to the export / save request functionality ?
Something like that ?
1- Hit the save request shortcut
2- Choose your format ( json / curl / wget / ... )
3- Choose your destination

Does it seems legit ?

**Comment by asciimoo** [comment]
@PouuleT awesome! Both that you'd like to implement the feature and the way you suggested. =)
I really like the idea of choosing format on response save. 👍
