### ISSUE TITLE
Can't run wuzz anymore. Fails with 'Error! Unknown command: redirects'

### ISSUE THREAD

**Issue by jgrossophoff** [asciimoo/wuzz#121]
Version:
Current master branch [50647fdd1216f822a6a621c15cce6a3fa0a4af4d]

Problem:
wuzz can't run anymore. Exits with
`Error! Unknown command: redirects`
regardless of flags/arguments.

Solution:
Check out to 763e9bee1f254bfb2635cce964a173032ae1c8bd, the commit before `Merge pull request #118 from iDevoid/redirect_restricted_mode_toggle` [9e930188a7ef73a746b6b021953579bd5900e891]

OS:
Manjaro Linux 18.1.1 / Juhraya

Shell:
zsh

Go version:
go version go1.13.3 linux/amd64

gocui and termbox-go dependencies are up to date.

**Comment by lfelia** [comment]
Having this same issue. Also used OPs remedy
