### ISSUE TITLE
Paste insert spaces between characters

### ISSUE THREAD

**Issue by Cupprum** [asciimoo/wuzz#127]
When i try to paster longer text then windows, it start putting spaces between characters, which are after the end of screen. So for example if Request Data window is 80 chars wide and i try to past 100 chars into it. First 80 chars will be okay, and the other 20 would have spaces between them. I tried this fix https://github.com/asciimoo/wuzz/issues/61 but nothing happend.

Looking forward for you reply, you built an amazing tool.

**Comment by asciimoo** [comment]
Thanks for the report, I can reproduce the issue. Further investigation required to fix the issue. While it isn't resolved, you can specify request data with the -d flag (e.g. `wuzz -d '************************************************************************************************************************'`)

**Comment by mosiman** [comment]
A bit late, but I work around this by using `ctrl+o` to open the editor and pasting in there. Hope it helps!

**Comment by tc-mgriff** [comment]
This issue happens for me as well. When i use the editor it get a bunch of terminal color values infront of what i added. Please create a real fix for this, updating asciimoo doesn't resolve it.

**Comment by Cupprum** [comment]
Closing as it seems like the project is dead.
