### ISSUE TITLE
Unrecognized import path

### ISSUE THREAD

**Issue by zPrototype** [asciimoo/wuzz#128]
I tried to install it via "go get github.com/asciimoo/wuzz" and it threw the following errors:
unrecognized import path "bytes": import path does not begin with hostname
unrecognized import path "compress/gzip": import path does not begin with hostname
unrecognized import path "crypto/tls": import path does not begin with hostname
unrecognized import path "encoding/json": import path does not begin with hostname
unrecognized import path "errors": import path does not begin with hostname
unrecognized import path "fmt": import path does not begin with hostname
unrecognized import path "regexp": import path does not begin with hostname
unrecognized import path "strings": import path does not begin with hostname
unrecognized import path "bufio": import path does not begin with hostname
unrecognized import path "encoding": import path does not begin with hostname
unrecognized import path "io": import path does not begin with hostname
unrecognized import path "io/ioutil": import path does not begin with hostname
unrecognized import path "math": import path does not begin with hostname
unrecognized import path "reflect": import path does not begin with hostname
unrecognized import path "sort": import path does not begin with hostname
unrecognized import path "strconv": import path does not begin with hostname
unrecognized import path "sync": import path does not begin with hostname
unrecognized import path "time": import path does not begin with hostname
unrecognized import path "unicode": import path does not begin with hostname
unrecognized import path "unicode/utf8": import path does not begin with hostname
unrecognized import path "os": import path does not begin with hostname
unrecognized import path "os/exec": import path does not begin with hostname
unrecognized import path "path/filepath": import path does not begin with hostname
unrecognized import path "runtime": import path does not begin with hostname
unrecognized import path "encoding/hex": import path does not begin with hostname
unrecognized import path "net/http": import path does not begin with hostname
unrecognized import path "net/url": import path does not begin with hostname
unrecognized import path "encoding/binary": import path does not begin with hostname
unrecognized import path "math/bits": import path does not begin with hostname
unrecognized import path "syscall": import path does not begin with hostname
unrecognized import path "unsafe": import path does not begin with hostname
unrecognized import path "unicode/utf16": import path does not begin with hostname
unrecognized import path "mime": import path does not begin with hostname
unrecognized import path "os/signal": import path does not begin with hostname
unrecognized import path "context": import path does not begin with hostname
unrecognized import path "net": import path does not begin with hostname
unrecognized import path "log": import path does not begin with hostname
unrecognized import path "mime/multipart": import path does not begin with hostname
unrecognized import path "path": import path does not begin with hostname
unrecognized import path "text/template": import path does not begin with hostname

Below is a snippet of my GOPATH config in my bashrc:
GOROOT=$HOME/.go
GOPATH=$HOME/go
GOBIN=$GOPATH/bin
export GOROOT
export GOPATH
export GOBIN

**Comment by asciimoo** [comment]
Seems like it cannot find the standard library. Can you install other go applications?
