### ISSUE TITLE
Request data not saved in history

### ISSUE THREAD

**Issue by nagy135** [asciimoo/wuzz#133]
My history doesnt preserve request body. Can you help me decide if this is not implemented yet or bug?
I m using AUR version 0.4.0

**Comment by asciimoo** [comment]
I think this isn't implemented yet, but it is indeed a useful and missing feature.

**Comment by nagy135** [comment]
Talking just about myself now, but this is the only reason I m not using this daily and am still wasting resources with electron postman ...
I would definitelly appreaciate having something like this, either save it in history or make some other way of storing body. I dont want this to feel harsh because this has a lot of potential to me ...tmux sessions where one window would be wuzz for every project ...please make my dream reality! :)

**Comment by asciimoo** [comment]
Thanks for the feedback, it's good to get use cases from users. =)

> tmux sessions where one window would be wuzz for every project

This is my typical workflow =)

**Comment by asciimoo** [comment]
Alright, seems like it was a quick fix, could you verify that it works as it is expected?

**Comment by asciimoo** [comment]
I've created new release binaries containing this feature: https://github.com/asciimoo/wuzz/releases/tag/v0.5.0 perhaps it makes testing easier.

**Comment by nagy135** [comment]
Ye you got it, one line to make me a user, thanks :)

**Comment by asciimoo** [comment]
Great, thanks for the review =]
