### ISSUE TITLE
Undefined error with unix.IoctlGetTermios when doing "go get"

### ISSUE THREAD

**Issue by mason-jones-ck** [asciimoo/wuzz#139]
```
$ go get github.com/asciimoo/wuzz
# github.com/mattn/go-isatty
.../src/github.com/mattn/go-isatty/isatty_bsd.go:10:12: undefined: unix.IoctlGetTermios
```
This is on a Mac, running `go version go1.14.3 darwin/amd64`. I did some searching and found a similar issue on another project (https://github.com/golang/go/issues/22688) and I tried rebuilding `golang.org/x/sys/unix` since it seemed to help some people there, but it didn't make a difference in this case.

Any suggestions would be great -- thanks.

**Comment by mason-jones-ck** [comment]
I realized the root of this error is of course in the `go-isatty` package, and found that there is an existing issue about this opened against it: https://github.com/mattn/go-isatty/issues/53

**Comment by mason-jones-ck** [comment]
However, that issue is over a year old, so it may be necessary to find a replacement for `go-isatty` to get this working...

**Comment by mattn** [comment]
This cause is that x/sys/unix was not support alpine but now support it. So I'll update dependencies in later.

**Comment by mason-jones-ck** [comment]
Just to close the loop on this in case others encounter it: there was something out of sync, apparently, in the golang.org/x/sys package which go-isatty didn't like. I removed that package and re-fetched go-isatty and it worked (documented in that issue). Since this didn't have anything to do with wuzz specifically, I'll close this but at least it's here for posterity.
