### ISSUE TITLE
Backspace key, toggles history in Windows 10

### ISSUE THREAD

**Issue by rahilwazir** [asciimoo/wuzz#16]
Pressing <kbd>Backspace</kbd> also toggles history view in Windows 10, unable to erase characters.

Go 1.7.4

**Comment by shpaker** [comment]
Sad bug. But you can modify string with shortcut CTRL + Backspace on Windows.

**Comment by asciimoo** [comment]
@rahilwazir, probably #15 solved it. Could you verify?

**Comment by shpaker** [comment]
Fixed. Checked on Windows 10 1607.

**Comment by asciimoo** [comment]
\o/
thanks

**Comment by ahmetoz** [comment]
No problem on Windows 10.. 
Thanks
