### ISSUE TITLE
Previous View (Shift+Tab) does not work in Windows 10

### ISSUE THREAD

**Issue by rahilwazir** [asciimoo/wuzz#17]
The hotkey for Previous view, <kbd>Shift+Tab</kbd> does not work in Windows 10

**Comment by rahilwazir** [comment]
Nevermind this is duplicate of https://github.com/asciimoo/wuzz/issues/1, closing...

**Comment by mattn** [comment]
FYI, wuzz uses [gocui](https://github.com/jroimartin/gocui). And [gocui](https://github.com/jroimartin/gocui) uses [termbox-go](https://github.com/nsf/termbox-go). [termbox-go](https://github.com/nsf/termbox-go) doesn't handle <kbd>Shift+Tab</kbd>.

**Comment by rahilwazir** [comment]
@mattn You mean doesn't handle in Windows right? In Linux it works.

Anyhow better report this issue there.
