### ISSUE TITLE
How to paste in "Copy as Curl" command?

### ISSUE THREAD

**Issue by bradparks** [asciimoo/wuzz#19]
I'm sure I'm missing something super obvious, but how do I paste in the "Copy as Curl" command I get from the network inspector?

I tried pasting it in, but it fails... and I tried starting wuzz and passing it as a command line arg, but that didnt' work either....

**Comment by asciimoo** [comment]
@bradparks simply paste the command to your shell and replace the `curl` command with `wuzz`.

**Comment by bradparks** [comment]
hey.... i should've tried that! but I did just try it and it doesnt seem to quite work... I took a random page from the net and copied it as curl. e.g.

> curl 'http://linuxcommand.org/wss0150.php' -H 'Pragma: akamai-x-get-client-ip, akamai-x-cache-on, akamai-x-cache-remote-on, akamai-x-check-cacheable, akamai-x-get-cache-key, akamai-x-get-extracted-values, akamai-x-get-nonces, akamai-x-get-ssl-client-session-id, akamai-x-get-true-cache-key, akamai-x-serial-no, akamai-x-feo-trace, akamai-x-get-request-id' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en,en-US;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3001.0 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Referer: https://www.google.ca/' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' --compressed



when I try and run `wuzz` with it, I get the url loading as "http://--compressed", and when I try removing `--compressed`, it then uses `http://max-age=0` as the url.... Does `wuzz` accept header params like this?

**Comment by asciimoo** [comment]
Ah, this is a  bug in command line argument parsing - it does not support the `--compress` flag.
Fixing, thanks.
