### ISSUE TITLE
long headers get messed up

### ISSUE THREAD

**Issue by justone** [asciimoo/wuzz#26]
First off, thanks for a great tool for exploring web apis.

I was using it to access Github's API and went to put in the auth header (eg `Authorization: Basic dGVzdHVzZXI6bm9wYXNzbm9wYXNzbm9wYXNzbm9wYXNzbm9wYXNzbm9wYXNzbm9wYXNzbm9wYXNz`), the display shows some characters on the next line:

![ndj homenet org - putty 2017-02-06 17 43 51](https://cloud.githubusercontent.com/assets/8082/22674272/e65eef1c-ec93-11e6-9c15-3168199c4f03.png)

If I adjust the characters to be on the line above, like this, it works:

![ndj homenet org - putty 2017-02-06 17 45 28](https://cloud.githubusercontent.com/assets/8082/22674293/1203f338-ec94-11e6-987d-f4b4ce76e739.png)

Thanks again.

**Comment by Benaiah** [comment]
@justone did you paste in the value? There seems to be some sort of issue when pasting - I can't repro the behavior when typing in a value manually. Not sure what the root cause is yet.

**Comment by justone** [comment]
Ah yes, it was when I was pasting. Sorry for leaving out that bit of information.

The nice thing is, once o get the value in there, I can keep firing requests without messing with it.

**Comment by casidiablo** [comment]
This is a very unfortunate bug. I guess if you have short auth tokens it is fine, but try to type a JWT token with lots of claims and you will go crazy.

**Comment by asciimoo** [comment]
Well, I can reproduce under linux, but don't understand.. If you paste a longer line than the view's width, it breaks the line as the first image shows. Works as expected, when I type a long line instead of pasting..
Most probably it is a bug in the `gocui` dependency, but still investigating.

**Comment by georgijd** [comment]
Hi there,

I found out that if the wrapping for the "headers" view is disabled this problem disappears. If you're happy with this behaviour, PR #35 does exactly that.
