### ISSUE TITLE
Support for END and HOME key

### ISSUE THREAD

**Issue by Eraden** [asciimoo/wuzz#27]
It would be nice to travel through URL using shortcuts.

Go to start:
* `HOME` 
* ~~`CTRL + LEFT`~~

Go to end:
* `END` 
* ~~`CTRL + RIGHT`~~

**Comment by Eraden** [comment]
`CTRL + LEFT/RIGHT` can't be supported due lack of gocui `CTRL` modifier per se.

**Comment by asciimoo** [comment]
implemented in #39
