### ISSUE TITLE
panic: invalid dimensions

### ISSUE THREAD

**Issue by umpc** [asciimoo/wuzz#3]
Because of this check in gocui: 

https://github.com/jroimartin/gocui/blob/6b3dc12c322589c2ecbeea58acc792d22f853455/gui.go#L128
```
if x0 >= x1 || y0 >= y1 {
	return nil, errors.New("invalid dimensions")
}
```

and because the main loop panics on error without attempting to restore the session:

https://github.com/asciimoo/wuzz/blob/master/wuzz.go#L681
```
if err := g.MainLoop(); err != nil && err != gocui.ErrQuit {
	log.Panicln(err)
}
```

Resizing the terminal window too small on at least macOS causes a panic.

Terminal:
<img width="364" alt="screen shot 2017-02-04 at 10 10 23 pm" src="https://cloud.githubusercontent.com/assets/5883661/22623373/c6d14dde-eb26-11e6-8957-48230dcfc6db.png">

Hyper:
![screen shot 2017-02-04 at 10 12 24 pm](https://cloud.githubusercontent.com/assets/5883661/22623382/325e95c0-eb27-11e6-9c75-503aad1a2cb0.png)

I can reproduce this in the default terminal emulator, Terminal, and in Hyper, which is what I use primarily.

**Comment by Benaiah** [comment]
I can confirm that this also occurs in Terminator in i3-gaps on Debian. Given the nature of the bug, it seems unlikely that there would be any software stack that *wouldn't* be able to reproduce the issue.
