### ISSUE TITLE
Can scroll way past the end of content

### ISSUE THREAD

**Issue by Depado** [asciimoo/wuzz#31]
Hey there, first of all, great software ! I just love it !
There's one odd thing though, I can keep scrolling using <kbd>Down</kbd> and <kbd>Page Down</kbd> way past the end of the content (headers, actual content, etc…). It's not critical and it's not even bothering, just a little weird :)

Thanks again for the great software !

**Comment by Benaiah** [comment]
This will be fixed when upstream is finished rewriting gocui's default editing mode - cf. jroimartin/gocui#60

@asciimoo, do you think we should try to fix this in wuzz or wait till upstream finishes the rewrite?
