### ISSUE TITLE
go install fialed

### ISSUE THREAD

**Issue by akkuman** [asciimoo/wuzz#56]
```bash
codecat@codecat-HP:~/mycode/go/src/github.com/asciimoo/wuzz$ go install
# github.com/nwidger/jsoncolor
../../nwidger/jsoncolor/jsoncolor.go:225: enc.SetEscapeHTML undefined (type *json.Encoder has no field or method SetEscapeHTML)
```

**Comment by akkuman** [comment]
my go version is go-1.6

**Comment by trobotham** [comment]
having the same exact issue

**Comment by asciimoo** [comment]
Seems, `jsoncolor` repo fails somehow. I cannot reproduce with go 1.7. @nwidger do you have any idea?

**Comment by rigrassm** [comment]
Think it's probably from the jsoncolor packages recent commit.: https://github.com/nwidger/jsoncolor/commit/3709c0e10f63511e81353d16590b6d414d3a13e4

**Comment by nwidger** [comment]
@asciimoo SetEscapeHTML was added in Go 1.7: https://golang.org/pkg/encoding/json/#Encoder.SetEscapeHTML which means wuzz needs Go >= 1.7 installed to build.

What is the minimum Go version that wuzz is expected to support?

**Comment by asciimoo** [comment]
> What is the minimum Go version that wuzz is expected to support?

Good question. Currently travis only tests go-1.7.5 and the latest go release.
What do you suggest?

**Comment by nwidger** [comment]
I believe this commit fixes the issue and allows jsoncolor to build on older Go versions: https://github.com/nwidger/jsoncolor/commit/75a6de4340e59be95f0884b9cebdda246e0fdf40

**Comment by trobotham** [comment]
confirmed, it works
