### ISSUE TITLE
Text pasted from clipboard gets messed

### ISSUE THREAD

**Issue by petersondmg** [asciimoo/wuzz#61]
When pasting a long text from clipboard (e.g. when pasting cookies from browser into headers section) it get messed

**Comment by mikegleasonjr** [comment]
So disappointed when I encountered this. I wanted to use this tool badly.

**Comment by asciimoo** [comment]
@petersondmg, @mikegleasonjr could you confirm that 0568b27 fixes the issue?

**Comment by mikegleasonjr** [comment]
```
$ go get github.com/asciimoo/wuzz
# github.com/asciimoo/wuzz
../../asciimoo/wuzz/wuzz.go:1256: g.ASCII undefined (type *gocui.Gui has no field or method ASCII)
```

**Comment by asciimoo** [comment]
@mikegleasonjr seems, your `gocui` dependency is out-of-date. Run `go get -u github.com/jroimartin/gocui`, to update the gocui package too.

**Comment by mikegleasonjr** [comment]
Amazing thanks. It is getting better and better 👍

**Comment by petersondmg** [comment]
Its working great! Many thanks! 😄
