### ISSUE TITLE
[Feature request] --json flag

### ISSUE THREAD

**Issue by mrpatiwi** [asciimoo/wuzz#70]
I would be really helpful to init `wuzz` with a `--json` / `-j` flag and automatically set the `Content-Type` and `Accept headers` set to `application/json`.

Example:
```sh
$ "$GOPATH/bin/wuzz" --json
```

> Related to https://github.com/asciimoo/wuzz/issues/9#issuecomment-280656891

**Comment by asciimoo** [comment]
A shell alias can be defined as a workaround.
E.g.: `alias wuzz-json='wuzz -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d'`, and you can execute `wuzz-json '{"x": 3}'` or `wuzz-json "$(cat xy.json)"`

**Comment by asciimoo** [comment]
added in 64a6272
