### ISSUE TITLE
F* keys can be tricky to use, so they should be customizable

### ISSUE THREAD

**Issue by chillum** [asciimoo/wuzz#82]
Many modern keyboards do not offer easy access to F* keys (they more tend to be multimedia ones by default) and pressing Fn+F3 is not very convenient in such case.

I believe, those keybindings are hardcoded now, but in future it's best to have them use-customizable as well.

**Comment by Benaiah** [comment]
@chillum These keybindings are already configurable - see https://github.com/asciimoo/wuzz/blob/master/config/config.go#L60-L67.

**Comment by chillum** [comment]
thanks. it seems like adding them to example config is not a bad idea

**Comment by Benaiah** [comment]
Sure - I'll reopen this as a docs issue and make a PR. The sample config should really have the whole default config in it for reference purposes.

**Comment by asciimoo** [comment]
added in 9ed7a7d4049a54bae8617d860921497d96ecf2be. Thank you @Benaiah
