### ISSUE TITLE
Improve infos about requests

### ISSUE THREAD

**Issue by wngmnheiko** [asciimoo/wuzz#89]
I'd like have more infos about the requests actually sent.

If I have the URL "http://google.com" I'd like to see the actual request sent (with the "/" as path).
If there is a redirect I'd like to see the actual redirects with all the data going back and forth.

**Comment by asciimoo** [comment]
@wngmnheiko you can disable the automatic redirection with the `-R`/`--disable-redirects` flags.

**Comment by wngmnheiko** [comment]
Had an older version running. But -R/--disable-redirects is nice. Now I want a shortcut to just follow the redirect, so that I can step through to the final destination and inspect all the intermediate requests.

**Comment by iDevoid** [comment]
Dear @asciimoo
I am first timer to contribute on open-source code, can I try to work on this? 
if so, what key would you like to add as the toggle?
I tried made some changes on your code, the result looks like this. (currently the toggle uses F12 on `ALL_VIEWS`)
please tell me your opinion :pray:
if you agreed with this, I'm gonna organize my code and then raise the PR. thank you

![Screenshot from 2019-10-03 22-43-46](https://user-images.githubusercontent.com/47969743/66142388-84f4d500-e62f-11e9-83ed-4b8d37e2d845.png)

**Comment by iDevoid** [comment]
Dear @asciimoo and @wngmnheiko
Would you mind checking if #118 fixed this issue?
if it doesn't please write down your opinion and advice. Thank you  :pray:

**Comment by asciimoo** [comment]
@iDevoid it is a great improvement, thanks.
