### ISSUE TITLE
Can't toggle history with Alt+H in Mac

### ISSUE THREAD

**Issue by yu-liao** [asciimoo/wuzz#92]
I `go get` the wuzz, and `go install`. I find the alt+H don't toggle history. In Mac, alt+H print `˙`.
The Mac is `Sierra`.

**Comment by asciimoo** [comment]
I can confirm, it isn't mac specific. It stops working after closing the external editor.
@yu-liao  could you verify that 8b38235 fixes the issue?

**Comment by yu-liao** [comment]
@asciimoo I pull the 8b38235, and go install. The bug is not fixed.

    $ git log -n 1
    commit 8b38235ec1aa0452793fc5761255e1a92e31eb20

**Comment by asciimoo** [comment]
@yu-liao what terminal emulator do you use?

**Comment by yu-liao** [comment]
@asciimoo The native shell under Mac.

**Comment by ieatmumble** [comment]
@yu-liao do you have the "Use option as meta key" option enabled?

**Comment by yu-liao** [comment]
@asciimoo You are right. After I enable "User option as meta key", alt + H toggle history.

**Comment by asciimoo** [comment]
It was answered by @ieatmumble - thank you. =]
