### ISSUE TITLE
Error: ./wuzz.go:1605: undefined: http.ErrUseLastResponse 

### ISSUE THREAD

**Issue by WellerQu** [asciimoo/wuzz#95]
when I typed "go get github.com/asciimoo/wuzz" in zsh, I get the error in title.
```
go get github.com/asciimoo/wuzz
# github.com/asciimoo/wuzz
./wuzz.go:1605: undefined: http.ErrUseLastResponse 
```

Help me, please. Thanks ^_^

**Comment by asciimoo** [comment]
@WellerQu try it with go version >=1.7
Feel free to reopen if it doesn't help

**Comment by WellerQu** [comment]
Thanks @asciimoo , I resolved it. You are right.
